# Generated by Django 4.1.5 on 2023-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='tags',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Picture'),
        ),
    ]
