# Generated by Django 4.1.5 on 2023-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_tags_news_tag_alter_news_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='about', verbose_name='About Image')),
                ('content', models.TextField(verbose_name='About')),
            ],
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
