# Generated by Django 4.1.5 on 2023-02-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_about_rename_news_post_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('facebook_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Facebook')),
                ('linkedin_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Linkedin')),
                ('instagram_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Instagram')),
            ],
        ),
    ]
