# Generated by Django 4.1.5 on 2023-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='sales@arcotama.com', max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_phone',
            field=models.IntegerField(default=1234567888, verbose_name='Mobile Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone'),
        ),
    ]
