# Generated by Django 4.1.5 on 2023-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_contact_email_contact_mobile_phone_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('status_message', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=25, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25, verbose_name='Email')),
            ],
        ),
    ]
