# Generated by Django 4.1.5 on 2023-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_contact_site_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='iframe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Iframe'),
        ),
    ]
