# Generated by Django 4.1.5 on 2023-03-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_contact_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(default='Arcotama', max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='iframe',
            field=models.TextField(blank=True, null=True, verbose_name='Iframe'),
        ),
    ]
