# Generated by Django 4.1.5 on 2023-03-21 01:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_contact_mobile_phone_alter_post_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=150, null=True, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='site_map_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Site Map'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content'),
        ),
    ]
