# Generated by Django 4.1.5 on 2023-03-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_delete_subscriber_alter_about_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
