# Generated by Django 4.1.5 on 2023-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_alter_post_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/about', verbose_name='About Image'),
        ),
    ]
