# Generated by Django 4.1.5 on 2023-03-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_alter_about_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='uploads/no-image.jpg', upload_to='uploads/%Y/%m/%d', verbose_name='Picture'),
        ),
    ]
